### ISSUE TITLE
Mermaid ELK integration not working in draw.io

### ISSUE THREAD

**Issue by Igzak** [jgraph/drawio#4685]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/dev/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
The ELK integration in draw.io appears to not function properly. When trying to use ELK for layouts, no layout is applied, and the diagrams do not adjust as expected.

**To Reproduce**
1. Open draw.io.
2. Attempt to use the ELK layout engine for diagram organization.
3. No layout is applied, and no error message is shown.
4. The diagram remains in its original state without adjustment.

**Expected behavior**
The diagrams should automatically adjust their layout according to the ELK engine when selected. This was functioning previously but now appears broken.

**Screenshots**
N/A

**draw.io version (In the Help->About menu of the draw.io editor):**
- draw.io version: v24.7.17

**Desktop (please complete the following information):**
 - OS: Linux Mint 22
 - Browser: Firefox
 - Browser Version: 130.0.1

**Smartphone (please complete the following information if applicable):**
 - Device: N/A
 - OS: N/A
 - Browser: N/A
 - Version: N/A

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
- yes

**Additional context**
This issue has been reported before in [issue #3634](https://github.com/jgraph/drawio/issues/3634) but seems to have resurfaced.

Can be checked with [this](https://github.com/jgraph/drawio/issues/3634#issuecomment-1590851016)

**Comment by xktder** [comment]
Mermaid ELK 集成在 draw.io 中不起作用

**Comment by davidjgraph** [comment]
It's broken at the moment. Mermaid isn't a core part of draw.io, it's support very much "as-is".

**Comment by Spenhouet** [comment]
Our Diagrams can be large and complex and dagre just isn't able to properly format this.
Elk would really help us.

**Comment by AlanCunningham** [comment]
Just in case it helps anyone, I found the latest version of Draw.io Desktop where the Elk renderer works is [v24.7.8](https://github.com/jgraph/drawio-desktop/releases/tag/v24.7.8).

**Comment by davidjgraph** [comment]
The is due to Mermaid spliting out elk into a separate package in 11.x

**Comment by clauslor** [comment]
Seems this is still not working in v28.2.8. Is there no workaround?

**Comment by ArturBaybulatov** [comment]
In the desktop macOS v30.2.6 version I get

> Uncaught TypeError: ElkLayout.runWithDialog is not a function

if a try to arrange a diagram via e.g. `Arrange -> Layout -> Vertical Flow…` menu item.

<img width="499" height="243" alt="Image" src="https://github.com/user-attachments/assets/0714342b-90d6-4c63-8f0b-05a8c97c4f8b" />

**Comment by davidjgraph** [comment]
ELK layout is in 30.2.7
